#!/usr/bin/env node
/**
 * scripts/generate-seo.js
 *
 * WHY THIS EXISTS: WhatsApp, Facebook, Telegram, LinkedIn and most other
 * link-preview scrapers fetch a URL's raw HTML and do NOT execute JavaScript.
 * The storefront's product.js already updates <title>/meta tags/JSON-LD after
 * the page loads (see applyProductSeo_ in assets/js/pages/product.js) — great
 * for Googlebot (which does render JS), useless for a WhatsApp preview.
 *
 * This script closes that gap WITHOUT a Node.js server: it's a one-off build
 * step (run locally or in CI, e.g. a GitHub Action) that calls the same
 * public Apps Script API the storefront already uses, and writes REAL static
 * HTML files — with the meta tags and JSON-LD already baked in — at the
 * clean URLs:
 *   /collections/{category}/products/{handle}/index.html
 *   /collections/{category}/index.html
 * plus sitemap-products.xml, sitemap-categories.xml, sitemap-brands.xml, and
 * a sitemap.xml index.
 *
 * Vercel serves an existing static file before falling back to the rewrite
 * rules in vercel.json, so: pages generated by this script get real
 * server-sent SEO tags immediately; any product added since the last build
 * still works instantly via the vercel.json rewrite → product.html shell,
 * which fetches live data client-side. Nothing is ever broken either way —
 * this script only ever adds files, it never deletes a working page.
 *
 * USAGE:
 *   1. Set ITZ_API_URL below (or as an env var) to your deployed Apps Script Web App URL.
 *   2. npm run build:seo
 *   3. Commit the generated /collections folder and sitemap*.xml, redeploy.
 *   4. Re-run after adding/editing products (or wire it into a scheduled GitHub Action).
 */

const fs = require("fs");
const path = require("path");

const API_URL = process.env.ITZ_API_URL || "https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec";
const FRONTEND_ROOT = path.join(__dirname, "..");

async function apiGet(action, params) {
  const query = new URLSearchParams(Object.assign({ action }, params || {}));
  const res = await fetch(`${API_URL}?${query.toString()}`);
  const json = await res.json();
  if (!json.success) throw new Error(`${action} failed: ${json.message}`);
  return json.data;
}

async function fetchAllProducts() {
  const products = [];
  let page = 1;
  for (;;) {
    const data = await apiGet("products.list", { page, limit: 100 });
    products.push(...data.items);
    if (page >= data.pages) return { products, categories: data.categories, brands: data.brands };
    page++;
  }
}

function xmlEscape(str) {
  return String(str || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function productJsonLd(product, site) {
  const url = site + product.canonicalPath;
  return [
    {
      "@context": "https://schema.org", "@type": "Product",
      name: product.name, description: product.seoDescription || product.description, sku: product.sku,
      image: product.images, brand: { "@type": "Brand", name: product.brand || "INAM TECH ZONE" },
      offers: {
        "@type": "Offer", url, priceCurrency: "PKR", price: product.discountPrice || product.price,
        availability: product.stock > 0 ? "https://schema.org/InStock" : "https://schema.org/OutOfStock",
      },
    },
    {
      "@context": "https://schema.org", "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: site + "/" },
        { "@type": "ListItem", position: 2, name: product.category, item: site + "/collections/" + product.categoryHandle },
        { "@type": "ListItem", position: 3, name: product.name, item: url },
      ],
    },
  ];
}

function renderProductPage(product, site, shell) {
  const title = product.seoTitle || `${product.name} — INAM TECH ZONE`;
  const description = (product.seoDescription || product.description || "").slice(0, 160);
  const url = site + product.canonicalPath;
  const image = product.ogImage || product.images[0] || "";
  const jsonLd = productJsonLd(product, site);

  let html = shell;
  html = html.replace(/<title>.*?<\/title>/, `<title>${xmlEscape(title)}</title>`);
  html = html.replace(
    /<link rel="stylesheet" href="\/assets\/css\/style\.css" \/>/,
    `<meta name="description" content="${xmlEscape(description)}" />
<link rel="canonical" href="${xmlEscape(url)}" />
<meta property="og:type" content="product" />
<meta property="og:title" content="${xmlEscape(title)}" />
<meta property="og:description" content="${xmlEscape(description)}" />
<meta property="og:url" content="${xmlEscape(url)}" />
<meta property="og:image" content="${xmlEscape(image)}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${xmlEscape(title)}" />
<meta name="twitter:description" content="${xmlEscape(description)}" />
<meta name="twitter:image" content="${xmlEscape(image)}" />
<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>
<link rel="stylesheet" href="/assets/css/style.css" />`
  );
  return html;
}

function renderCategoryPage(category, products, site, shell) {
  const title = `${category.name} — INAM TECH ZONE`;
  const description = `Shop ${category.name} at INAM TECH ZONE — ${products.length} product(s), fast delivery, easy order tracking.`;
  const url = `${site}/collections/${category.slug}`;
  const jsonLd = {
    "@context": "https://schema.org", "@type": "ItemList",
    itemListElement: products.slice(0, 20).map((p, i) => ({
      "@type": "ListItem", position: i + 1, url: site + p.canonicalPath, name: p.name,
    })),
  };

  let html = shell;
  html = html.replace(/<title>.*?<\/title>/, `<title>${xmlEscape(title)}</title>`);
  html = html.replace(
    /<link rel="stylesheet" href="\/assets\/css\/style\.css" \/>/,
    `<meta name="description" content="${xmlEscape(description)}" />
<link rel="canonical" href="${xmlEscape(url)}" />
<meta property="og:type" content="website" />
<meta property="og:title" content="${xmlEscape(title)}" />
<meta property="og:description" content="${xmlEscape(description)}" />
<meta property="og:url" content="${xmlEscape(url)}" />
<script type="application/ld+json">${JSON.stringify(jsonLd)}</script>
<link rel="stylesheet" href="/assets/css/style.css" />`
  );
  return html;
}

function buildSitemapXml(urls) {
  const items = urls.map((u) => `  <url><loc>${xmlEscape(u.loc)}</loc>${u.priority ? `<priority>${u.priority}</priority>` : ""}</url>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${items}\n</urlset>\n`;
}

function buildSitemapIndex(sitemapFiles, site) {
  const items = sitemapFiles.map((f) => `  <sitemap><loc>${site}/${f}</loc></sitemap>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${items}\n</sitemapindex>\n`;
}

async function main() {
  console.log(`Fetching settings and catalog from ${API_URL} ...`);
  const settings = await apiGet("settings.get", {});
  const site = (settings.siteUrl || "https://inamtechzone.example.com").replace(/\/$/, "");
  const { products, categories, brands } = await fetchAllProducts();
  console.log(`Fetched ${products.length} products, ${categories.length} categories, ${brands.length} brands.`);

  const productShell = fs.readFileSync(path.join(FRONTEND_ROOT, "product.html"), "utf8");
  const shopShell = fs.readFileSync(path.join(FRONTEND_ROOT, "shop.html"), "utf8");

  let productPages = 0;
  for (const product of products) {
    if (!product.categoryHandle || !product.slug) continue;
    const dir = path.join(FRONTEND_ROOT, "collections", product.categoryHandle, "products", product.slug);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "index.html"), renderProductPage(product, site, productShell));
    productPages++;
  }
  console.log(`Generated ${productPages} static product pages.`);

  let categoryPages = 0;
  for (const category of categories) {
    const catProducts = products.filter((p) => p.categoryHandle === category.slug);
    const dir = path.join(FRONTEND_ROOT, "collections", category.slug);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "index.html"), renderCategoryPage(category, catProducts, site, shopShell));
    categoryPages++;
  }
  console.log(`Generated ${categoryPages} static category pages.`);

  // Sitemaps
  const productUrls = products.map((p) => ({ loc: site + p.canonicalPath, priority: "0.8" }));
  const categoryUrls = categories.map((c) => ({ loc: `${site}/collections/${c.slug}`, priority: "0.7" }));
  const brandUrls = brands.map((b) => ({ loc: `${site}/shop.html?brand=${b.slug}`, priority: "0.5" }));

  fs.writeFileSync(path.join(FRONTEND_ROOT, "sitemap-products.xml"), buildSitemapXml(productUrls));
  fs.writeFileSync(path.join(FRONTEND_ROOT, "sitemap-categories.xml"), buildSitemapXml(categoryUrls));
  fs.writeFileSync(path.join(FRONTEND_ROOT, "sitemap-brands.xml"), buildSitemapXml(brandUrls));
  fs.writeFileSync(
    path.join(FRONTEND_ROOT, "sitemap.xml"),
    buildSitemapIndex(["sitemap-products.xml", "sitemap-categories.xml", "sitemap-brands.xml", "sitemap-static.xml"], site)
  );
  fs.writeFileSync(
    path.join(FRONTEND_ROOT, "sitemap-static.xml"),
    buildSitemapXml([
      { loc: site + "/index.html", priority: "1.0" },
      { loc: site + "/shop.html", priority: "0.9" },
      { loc: site + "/track-order.html", priority: "0.5" },
      { loc: site + "/wishlist.html", priority: "0.3" },
      { loc: site + "/compare.html", priority: "0.3" },
    ])
  );
  console.log("Generated sitemap.xml (index) + 4 child sitemaps.");
  console.log("Done. Commit the /collections folder and sitemap*.xml, then redeploy.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
